-- ========================================
-- 카테고리
-- ========================================
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (1, '커피(HOT)', 1);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (2, '커피(ICE)', 2);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (3, '라떼/논커피', 3);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (4, '프라푸치노/블렌디드', 4);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (5, '티(TEA)', 5);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (6, '에이드/주스', 6);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (7, '디저트', 7);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (8, '베이커리', 8);
MERGE INTO CATEGORY (ID, NAME, DISPLAY_ORDER) KEY(ID) VALUES (9, '샌드위치/푸드', 9);

-- ========================================
-- 매장 / 테이블
-- ========================================
MERGE INTO STORE (ID, NAME, STORE_CODE, CREATED_AT) KEY(ID) VALUES (1, '카페 강남점', 'CAFE01', NOW());
MERGE INTO STORE (ID, NAME, STORE_CODE, CREATED_AT) KEY(ID) VALUES (2, '카페 판교점', 'CAFE02', NOW());

MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (1, 1, 1, '1234');
MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (2, 1, 2, '1234');
MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (3, 1, 3, '1234');
MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (4, 1, 4, '1234');
MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (5, 2, 1, '1234');
MERGE INTO TABLE_INFO (ID, STORE_ID, TABLE_NUMBER, PASSWORD) KEY(ID) VALUES (6, 2, 2, '1234');

-- ========================================
-- 커피(HOT) - 카테고리 1
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (1, 1, '아메리카노', 4500, '진한 에스프레소에 뜨거운 물을 더한 깔끔한 커피', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (2, 1, '카페 라떼', 5000, '에스프레소와 부드러운 스팀 밀크의 조화', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (3, 1, '카푸치노', 5000, '에스프레소에 풍성한 우유 거품을 올린 커피', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (4, 1, '카페 모카', 5500, '초콜릿과 에스프레소가 어우러진 달콤한 커피', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (5, 1, '바닐라 라떼', 5500, '바닐라 시럽과 에스프레소, 스팀 밀크의 조화', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (6, 1, '카라멜 마키아또', 5900, '바닐라 시럽, 스팀 밀크 위에 카라멜 드리즐', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (7, 1, '화이트 초콜릿 모카', 5900, '화이트 초콜릿과 에스프레소의 부드러운 만남', 7, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (8, 1, '돌체 라떼', 5900, '연유의 달콤함이 더해진 라떼', 8, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (9, 1, '헤이즐넛 라떼', 5500, '고소한 헤이즐넛 시럽이 들어간 라떼', 9, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (10, 1, '에스프레소', 3500, '깊고 진한 에스프레소 원샷', 10, NOW());

-- ========================================
-- 커피(ICE) - 카테고리 2
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (11, 2, '아이스 아메리카노', 4500, '진한 에스프레소에 시원한 얼음과 물', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (12, 2, '아이스 카페 라떼', 5000, '에스프레소와 차가운 우유의 시원한 조합', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (13, 2, '아이스 카페 모카', 5500, '초콜릿, 에스프레소, 차가운 우유의 달콤한 조합', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (14, 2, '아이스 바닐라 라떼', 5500, '바닐라 시럽과 에스프레소, 차가운 우유', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (15, 2, '아이스 카라멜 마키아또', 5900, '시원한 바닐라 라떼 위에 카라멜 드리즐', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (16, 2, '아이스 돌체 라떼', 5900, '연유의 달콤함이 더해진 아이스 라떼', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (17, 2, '콜드 브루', 5000, '24시간 저온 추출한 부드러운 커피', 7, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (18, 2, '콜드 브루 라떼', 5500, '콜드 브루에 신선한 우유를 더한 라떼', 8, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (19, 2, '아이스 헤이즐넛 라떼', 5500, '고소한 헤이즐넛 시럽의 아이스 라떼', 9, NOW());

-- ========================================
-- 라떼/논커피 - 카테고리 3
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (20, 3, '녹차 라떼', 5900, '고급 말차와 부드러운 우유의 조화', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (21, 3, '고구마 라떼', 5900, '달콤한 고구마와 우유의 부드러운 라떼', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (22, 3, '초콜릿 라떼', 5500, '진한 초콜릿과 우유의 달콤한 조합', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (23, 3, '딸기 라떼', 6300, '신선한 딸기와 우유의 상큼한 라떼', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (24, 3, '토피넛 라떼', 5900, '토피넛 시럽과 우유의 고소한 라떼', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (25, 3, '흑임자 라떼', 5900, '고소한 흑임자와 우유의 한국적인 라떼', 6, NOW());

-- ========================================
-- 프라푸치노/블렌디드 - 카테고리 4
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (26, 4, '자바 칩 프라푸치노', 6300, '초콜릿 칩과 커피가 어우러진 프라푸치노', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (27, 4, '카라멜 프라푸치노', 5900, '카라멜과 커피의 달콤한 프라푸치노', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (28, 4, '모카 프라푸치노', 5900, '초콜릿과 커피의 진한 프라푸치노', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (29, 4, '바닐라 크림 프라푸치노', 5400, '바닐라 크림의 부드러운 논커피 프라푸치노', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (30, 4, '망고 패션 블렌디드', 5900, '망고와 패션프루트의 상큼한 블렌디드', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (31, 4, '딸기 요거트 블렌디드', 6300, '딸기와 요거트의 상큼한 블렌디드', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (32, 4, '피치 레몬 블렌디드', 5900, '복숭아와 레몬의 상큼한 블렌디드', 7, NOW());

-- ========================================
-- 티(TEA) - 카테고리 5
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (33, 5, '얼 그레이 티', 4100, '베르가못 향이 감도는 클래식 홍차', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (34, 5, '캐모마일 블렌드 티', 4100, '은은한 캐모마일 허브티', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (35, 5, '페퍼민트 티', 4100, '상쾌한 페퍼민트 허브티', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (36, 5, '유자 민트 티', 5900, '상큼한 유자와 민트의 조화', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (37, 5, '차이 티 라떼', 5400, '이국적인 스파이스와 스팀 밀크', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (38, 5, '제주 말차 라떼', 6100, '제주산 말차와 부드러운 우유', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (39, 5, '루이보스 티', 4100, '카페인 없는 부드러운 루이보스', 7, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (40, 5, '자스민 그린 티', 4100, '은은한 자스민 향의 녹차', 8, NOW());

-- ========================================
-- 에이드/주스 - 카테고리 6
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (41, 6, '레몬 에이드', 5400, '신선한 레몬과 탄산의 상큼한 에이드', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (42, 6, '자몽 에이드', 5700, '자몽과 탄산의 새콤달콤한 에이드', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (43, 6, '청포도 에이드', 5400, '청포도의 달콤한 에이드', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (44, 6, '패션프루트 에이드', 5700, '패션프루트의 열대 과일 에이드', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (45, 6, '딸기 주스', 5900, '신선한 딸기를 갈아 만든 주스', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (46, 6, '키위 주스', 5900, '새콤달콤한 키위 주스', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (47, 6, '한라봉 주스', 6300, '제주 한라봉의 상큼한 주스', 7, NOW());

-- ========================================
-- 디저트 - 카테고리 7
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (48, 7, '뉴욕 치즈케이크', 6500, '진한 크림치즈의 클래식 치즈케이크', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (49, 7, '티라미수', 6500, '마스카포네 크림과 에스프레소의 조화', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (50, 7, '초콜릿 브라우니', 4500, '진한 초콜릿의 촉촉한 브라우니', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (51, 7, '마카롱 세트(3종)', 5500, '바닐라, 초콜릿, 딸기 마카롱 세트', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (52, 7, '바스크 치즈케이크', 6900, '겉은 캐러멜, 속은 부드러운 바스크식 치즈케이크', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (53, 7, '레몬 타르트', 5500, '상큼한 레몬 커드와 바삭한 타르트', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (54, 7, '크렘 브륄레', 6500, '바닐라 커스터드 위 캐러멜 크러스트', 7, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (55, 7, '아이스크림(바닐라)', 4000, '부드러운 바닐라 아이스크림', 8, NOW());

-- ========================================
-- 베이커리 - 카테고리 8
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (56, 8, '크루아상', 3800, '겉은 바삭하고 속은 부드러운 버터 크루아상', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (57, 8, '초코 크루아상', 4200, '초콜릿이 들어간 크루아상', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (58, 8, '블루베리 머핀', 3500, '블루베리가 가득한 촉촉한 머핀', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (59, 8, '바나나 브레드', 4500, '바나나의 달콤함이 가득한 브레드', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (60, 8, '스콘(플레인)', 3500, '담백하고 고소한 플레인 스콘', 5, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (61, 8, '시나몬 롤', 4500, '시나몬 향 가득한 달콤한 롤', 6, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (62, 8, '소금빵', 3200, '바삭한 겉면과 버터 풍미의 소금빵', 7, NOW());

-- ========================================
-- 샌드위치/푸드 - 카테고리 9
-- ========================================
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (63, 9, '햄 치즈 샌드위치', 5500, '햄과 치즈가 들어간 클래식 샌드위치', 1, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (64, 9, 'BLT 샌드위치', 6200, '베이컨, 양상추, 토마토 샌드위치', 2, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (65, 9, '에그 샐러드 샌드위치', 5800, '부드러운 에그 샐러드 샌드위치', 3, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (66, 9, '치킨 파니니', 6500, '그릴에 구운 치킨 파니니', 4, NOW());
MERGE INTO MENU (ID, CATEGORY_ID, NAME, PRICE, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) KEY(ID) VALUES (67, 9, '카프레제 샌드위치', 6200, '모짜렐라, 토마토, 바질 샌드위치', 5, NOW());

-- ========================================
-- 옵션 그룹
-- ========================================
-- 아메리카노(HOT)
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (1, 1, '사이즈', 'SINGLE', TRUE, 1);
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (2, 1, '샷 추가', 'SINGLE', FALSE, 2);
-- 카페 라떼(HOT)
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (3, 2, '사이즈', 'SINGLE', TRUE, 1);
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (4, 2, '샷 추가', 'SINGLE', FALSE, 2);
-- 카페 모카(HOT)
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (5, 4, '사이즈', 'SINGLE', TRUE, 1);
-- 아이스 아메리카노
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (6, 11, '사이즈', 'SINGLE', TRUE, 1);
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (7, 11, '샷 추가', 'SINGLE', FALSE, 2);
-- 아이스 카페 라떼
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (8, 12, '사이즈', 'SINGLE', TRUE, 1);
-- 콜드 브루
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (9, 17, '사이즈', 'SINGLE', TRUE, 1);
-- 녹차 라떼
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (10, 20, '온도', 'SINGLE', TRUE, 1);
-- 자바 칩 프라푸치노
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (11, 26, '사이즈', 'SINGLE', TRUE, 1);
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (12, 26, '토핑', 'MULTIPLE', FALSE, 2);
-- 제주 말차 라떼
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (13, 38, '온도', 'SINGLE', TRUE, 1);
-- 레몬 에이드
MERGE INTO OPTION_GROUP (ID, MENU_ID, NAME, SELECTION_TYPE, REQUIRED, DISPLAY_ORDER) KEY(ID) VALUES (14, 41, '탄산', 'SINGLE', FALSE, 1);

-- ========================================
-- 옵션
-- ========================================
-- 사이즈 (그룹1 - 아메리카노 HOT)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (1, 1, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (2, 1, 'Large', 500, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (3, 1, 'Extra Large', 1000, 3);
-- 샷 추가 (그룹2 - 아메리카노 HOT)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (4, 2, '1샷 추가', 600, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (5, 2, '2샷 추가', 1200, 2);
-- 사이즈 (그룹3 - 카페 라떼 HOT)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (6, 3, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (7, 3, 'Large', 500, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (8, 3, 'Extra Large', 1000, 3);
-- 샷 추가 (그룹4 - 카페 라떼 HOT)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (9, 4, '1샷 추가', 600, 1);
-- 사이즈 (그룹5 - 카페 모카 HOT)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (10, 5, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (11, 5, 'Large', 500, 2);
-- 사이즈 (그룹6 - 아이스 아메리카노)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (12, 6, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (13, 6, 'Large', 500, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (14, 6, 'Extra Large', 1000, 3);
-- 샷 추가 (그룹7 - 아이스 아메리카노)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (15, 7, '1샷 추가', 600, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (16, 7, '2샷 추가', 1200, 2);
-- 사이즈 (그룹8 - 아이스 카페 라떼)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (17, 8, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (18, 8, 'Large', 500, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (19, 8, 'Extra Large', 1000, 3);
-- 사이즈 (그룹9 - 콜드 브루)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (20, 9, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (21, 9, 'Large', 500, 2);
-- 온도 (그룹10 - 녹차 라떼)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (22, 10, 'HOT', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (23, 10, 'ICE', 0, 2);
-- 사이즈 (그룹11 - 자바 칩 프라푸치노)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (24, 11, 'Regular', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (25, 11, 'Large', 500, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (26, 11, 'Extra Large', 1000, 3);
-- 토핑 (그룹12 - 자바 칩 프라푸치노)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (27, 12, '휘핑크림 추가', 600, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (28, 12, '자바 칩 추가', 800, 2);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (29, 12, '초콜릿 드리즐', 600, 3);
-- 온도 (그룹13 - 제주 말차 라떼)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (30, 13, 'HOT', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (31, 13, 'ICE', 0, 2);
-- 탄산 (그룹14 - 레몬 에이드)
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (32, 14, '탄산 있음', 0, 1);
MERGE INTO OPTION (ID, OPTION_GROUP_ID, NAME, ADDITIONAL_PRICE, DISPLAY_ORDER) KEY(ID) VALUES (33, 14, '탄산 없음', 0, 2);
